/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homely;

import java.awt.image.BufferedImage;
import java.io.File;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author indbr
 */
public class MainFrame extends javax.swing.JFrame {
    private final String url = "jdbc:mysql://localhost:3306/homely";
    private final String user = "root";
    private final String password = "SamberGledek1";
    NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
    private class FormState {
        public String namaPemesan, area, tipeRumah;
        public int hargaTanah = 0, hargaBangunan = 0, 
            luasTanahAsli = 0, luasTanahTersedia = 0,
            dp = 0, lamaCicilan = 1;
        public boolean setuju = false;
        private int harga,ppn,cicilanBln;
        void calcHarga(){
            harga = (luasTanahTersedia * hargaTanah) + hargaBangunan;
            ppn = harga/10;
            cicilanBln = (harga + ppn - dp)/lamaCicilan;
        }
        int getHarga(){
            return harga;
        }
        int getPPn(){
            return ppn;
        }
        int getCicilanBln(){
            return cicilanBln;
        }
    }
    private FormState internalState = new FormState();
    private List<DataPenjualan> dataTabel = new ArrayList();
    private List<DataPenjualan> dataTabelPencarian = new ArrayList();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipeRumahGroup = new javax.swing.ButtonGroup();
        PenjualanRumahPanel = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        luasTanahAsliTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        luasTanahTersediaTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hargaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dpTextField = new javax.swing.JTextField();
        namaPemesanTextField = new javax.swing.JTextField();
        lamaCicilanTextField = new javax.swing.JTextField();
        hargaTanahTextField = new javax.swing.JTextField();
        ppnTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cicilanTextField = new javax.swing.JTextField();
        areaComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        setujuCheckBox = new javax.swing.JCheckBox();
        hargaBangunanTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        prosesButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        clearButton = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        BufferedImage myPicture = null;
        try{
            myPicture = ImageIO.read(new File("C:\\Users\\indbr\\Documents\\NetBeansProjects\\Homely\\assets\\image\\house.jpeg"));
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        imageLabel = new javax.swing.JLabel(new ImageIcon(myPicture));
        tampilDataPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarPenjualanTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jumlahRumahTerjualTextField = new javax.swing.JTextField();
        totalPenjualanRumahTextField = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        cariDataPanel = new javax.swing.JPanel();
        cariDataSubpanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cariPemesanTextField = new javax.swing.JTextField();
        cariAreaTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        daftarPenjualanTable1 = new javax.swing.JTable();
        jumlahRumahTerjualTextField1 = new javax.swing.JTextField();
        totalPenjualanRumahTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PenjualanRumahMenuItem = new javax.swing.JMenuItem();
        tampilDataMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipeRumahGroup.add(jRadioButton3);
        jRadioButton3.setText("Tipe-54");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Luas Tanah Asli");

        luasTanahAsliTextField.setEditable(false);
        luasTanahAsliTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasTanahAsliTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Tanah Tersedia");

        luasTanahTersediaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasTanahTersediaTextFieldActionPerformed(evt);
            }
        });
        luasTanahTersediaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                luasTanahTersediaTextFieldKeyTyped(evt);
            }
        });

        jLabel8.setText("Harga");

        hargaTextField.setEditable(false);
        hargaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("DP");

        jLabel10.setText("Lama Cicilan");

        jLabel11.setText("PPN (10%)");

        jLabel1.setText("Nama Pemesan");

        jLabel12.setText("Cicilan/bln");

        jLabel2.setText("Harga Tanah/m2");

        dpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpTextFieldActionPerformed(evt);
            }
        });
        dpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dpTextFieldKeyTyped(evt);
            }
        });

        namaPemesanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPemesanTextFieldActionPerformed(evt);
            }
        });
        namaPemesanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaPemesanTextFieldKeyTyped(evt);
            }
        });

        lamaCicilanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaCicilanTextFieldActionPerformed(evt);
            }
        });
        lamaCicilanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lamaCicilanTextFieldKeyTyped(evt);
            }
        });

        hargaTanahTextField.setEditable(false);
        hargaTanahTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaTanahTextFieldActionPerformed(evt);
            }
        });

        ppnTextField.setEditable(false);
        ppnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppnTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Area");

        cicilanTextField.setEditable(false);
        cicilanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cicilanTextFieldActionPerformed(evt);
            }
        });

        areaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bougenvile", "Melati", "Flamboyan" }));
        areaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboBoxActionPerformed(evt);
            }
        });

        jLabel13.setText("Bulan");

        jLabel4.setText("Harga Bangunan");

        setujuCheckBox.setText("Setuju");
        setujuCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setujuCheckBoxActionPerformed(evt);
            }
        });

        hargaBangunanTextField.setEditable(false);
        hargaBangunanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaBangunanTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipe Rumah");

        prosesButton.setText("Proses");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        tipeRumahGroup.add(jRadioButton1);
        jRadioButton1.setText("Tipe-36");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        tipeRumahGroup.add(jRadioButton2);
        jRadioButton2.setText("Tipe-45");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imageLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        imageLabel.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout PenjualanRumahPanelLayout = new javax.swing.GroupLayout(PenjualanRumahPanel);
        PenjualanRumahPanel.setLayout(PenjualanRumahPanelLayout);
        PenjualanRumahPanelLayout.setHorizontalGroup(
            PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPemesanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaTanahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(54, 54, 54)
                                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cicilanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ppnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(lamaCicilanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setujuCheckBox)
                                    .addComponent(jLabel13))))
                        .addGap(0, 141, Short.MAX_VALUE))
                    .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jLabel5)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                                .addGap(47, 47, 47)
                                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hargaBangunanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(luasTanahAsliTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(luasTanahTersediaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                .addComponent(prosesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(simpanButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PenjualanRumahPanelLayout.setVerticalGroup(
            PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                        .addComponent(hargaBangunanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(luasTanahAsliTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(luasTanahTersediaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(9, 9, 9)
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(dpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lamaCicilanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ppnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cicilanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setujuCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prosesButton)
                            .addComponent(simpanButton)
                            .addComponent(clearButton)))
                    .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(namaPemesanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hargaTanahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(PenjualanRumahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(areaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PenjualanRumahPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        tampilDataPanel.setPreferredSize(new java.awt.Dimension(809, 403));

        daftarPenjualanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pemesan", "Area", "Tipe Rumah", "Luas Tanah", "Harga", "Lama Cicilan", "Cicilan/bln"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        daftarPenjualanTable.setPreferredSize(new java.awt.Dimension(809, 235));
        daftarPenjualanTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(daftarPenjualanTable);

        jLabel14.setText("Jumlah Rumah Terjual");

        jLabel15.setText("Total Penjualan Rumah");

        jumlahRumahTerjualTextField.setEditable(false);

        totalPenjualanRumahTextField.setEditable(false);

        jToggleButton1.setText("cetak");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tampilDataPanelLayout = new javax.swing.GroupLayout(tampilDataPanel);
        tampilDataPanel.setLayout(tampilDataPanelLayout);
        tampilDataPanelLayout.setHorizontalGroup(
            tampilDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tampilDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataPanelLayout.createSequentialGroup()
                        .addGap(0, 453, Short.MAX_VALUE)
                        .addGroup(tampilDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tampilDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jumlahRumahTerjualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tampilDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(totalPenjualanRumahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE))
                .addContainerGap())
        );
        tampilDataPanelLayout.setVerticalGroup(
            tampilDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tampilDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tampilDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jumlahRumahTerjualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tampilDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(totalPenjualanRumahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tampilDataPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jToggleButton1)))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        cariDataPanel.setPreferredSize(new java.awt.Dimension(809, 403));

        cariDataSubpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Data"));
        cariDataSubpanel.setToolTipText("");
        cariDataSubpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cariDataSubpanel.setName("Cari Data"); // NOI18N

        jLabel16.setText("Nama Pemesan");

        jLabel17.setText("Nama Area");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cariDataSubpanelLayout = new javax.swing.GroupLayout(cariDataSubpanel);
        cariDataSubpanel.setLayout(cariDataSubpanelLayout);
        cariDataSubpanelLayout.setHorizontalGroup(
            cariDataSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cariDataSubpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cariDataSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(cariDataSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cariDataSubpanelLayout.createSequentialGroup()
                        .addComponent(cariPemesanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(cariAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        cariDataSubpanelLayout.setVerticalGroup(
            cariDataSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cariDataSubpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cariDataSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cariPemesanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(cariDataSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cariAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        daftarPenjualanTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pemesan", "Area", "Tipe Rumah", "Luas Tanah", "Harga", "Lama Cicilan", "Cicilan/bln"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        daftarPenjualanTable1.setPreferredSize(new java.awt.Dimension(809, 235));
        daftarPenjualanTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(daftarPenjualanTable1);

        jumlahRumahTerjualTextField1.setEditable(false);

        totalPenjualanRumahTextField1.setEditable(false);

        jLabel19.setText("Total Penjualan Rumah");

        jLabel18.setText("Jumlah Rumah Terjual");

        javax.swing.GroupLayout cariDataPanelLayout = new javax.swing.GroupLayout(cariDataPanel);
        cariDataPanel.setLayout(cariDataPanelLayout);
        cariDataPanelLayout.setHorizontalGroup(
            cariDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cariDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cariDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(cariDataPanelLayout.createSequentialGroup()
                        .addComponent(cariDataSubpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 450, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cariDataPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cariDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cariDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jumlahRumahTerjualTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cariDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(totalPenjualanRumahTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
        );
        cariDataPanelLayout.setVerticalGroup(
            cariDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cariDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cariDataSubpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cariDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jumlahRumahTerjualTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cariDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(totalPenjualanRumahTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Login");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pilihan");

        PenjualanRumahMenuItem.setText("Penjualan Rumah");
        PenjualanRumahMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanRumahMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(PenjualanRumahMenuItem);

        tampilDataMenuItem.setText("Tampil Data");
        tampilDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilDataMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(tampilDataMenuItem);

        jMenuItem3.setText("Cari Data");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tampilDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PenjualanRumahPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cariDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PenjualanRumahPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tampilDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tampilDataPanel.setVisible(false);
        cariDataPanel.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        internalState.tipeRumah = jRadioButton1.getText();
        internalState.luasTanahAsli = 120;
        luasTanahAsliTextField.setText(""+internalState.luasTanahAsli);
        internalState.calcHarga();
        displayHarga();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        internalState.tipeRumah = jRadioButton1.getText();
        internalState.luasTanahAsli = 90;
        luasTanahAsliTextField.setText(""+internalState.luasTanahAsli);
        internalState.calcHarga();
        displayHarga();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void hargaBangunanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaBangunanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBangunanTextFieldActionPerformed

    private void setujuCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setujuCheckBoxActionPerformed
        // TODO add your handling code here:
        if (!internalState.setuju){
            JOptionPane.showMessageDialog(this, "Pelanggan Konfirm/Setuju");
            internalState.setuju = !internalState.setuju;
        }
    }//GEN-LAST:event_setujuCheckBoxActionPerformed

    private void cicilanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cicilanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cicilanTextFieldActionPerformed

    private void ppnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppnTextFieldActionPerformed

    private void hargaTanahTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTanahTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTanahTextFieldActionPerformed

    private void lamaCicilanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaCicilanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaCicilanTextFieldActionPerformed

    private void namaPemesanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemesanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemesanTextFieldActionPerformed

    private void dpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpTextFieldActionPerformed
        // TODO add your handling code here:
        try {
            internalState.dp = Integer.parseInt(dpTextField.getText());
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
        internalState.calcHarga();
        displayHarga();
    }//GEN-LAST:event_dpTextFieldActionPerformed

    private void hargaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaTextFieldActionPerformed

    private void luasTanahTersediaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasTanahTersediaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasTanahTersediaTextFieldActionPerformed

    private void luasTanahAsliTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasTanahAsliTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasTanahAsliTextFieldActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        internalState.tipeRumah = jRadioButton1.getText();
        internalState.luasTanahAsli = 140;
        luasTanahAsliTextField.setText(""+internalState.luasTanahAsli);
        internalState.calcHarga();
        displayHarga();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void PenjualanRumahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanRumahMenuItemActionPerformed
        // TODO add your handling code here:
        PenjualanRumahPanel.setVisible(true);
        tampilDataPanel.setVisible(false);
        cariDataPanel.setVisible(false);
    }//GEN-LAST:event_PenjualanRumahMenuItemActionPerformed

    private void tampilDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilDataMenuItemActionPerformed
        // TODO add your handling code here:
        PenjualanRumahPanel.setVisible(false);
        tampilDataPanel.setVisible(true);
        cariDataPanel.setVisible(false);
        fetchDataPenjualan();
    }//GEN-LAST:event_tampilDataMenuItemActionPerformed

    private void areaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboBoxActionPerformed
        // TODO add your handling code here:
        String area = areaComboBox.getSelectedItem().toString();
        switch (area){
            case "Bougenvile":
                internalState.hargaTanah = 500000;
                internalState.hargaBangunan = 90000000;
                hargaTanahTextField.setText(nf.format(internalState.hargaTanah));
                hargaBangunanTextField.setText(nf.format(internalState.hargaBangunan));
                break;
            case "Melati" :
                internalState.hargaTanah = 600000;
                internalState.hargaBangunan = 120000000;
                hargaTanahTextField.setText(nf.format(internalState.hargaTanah));
                hargaBangunanTextField.setText(nf.format(internalState.hargaBangunan));
                break;
            case "Flamboyan" :
                internalState.hargaTanah = 700000;
                internalState.hargaBangunan = 150000000;
                hargaTanahTextField.setText(nf.format(internalState.hargaTanah));
                hargaBangunanTextField.setText(nf.format(internalState.hargaBangunan));
                break;
        }
        internalState.area = area;
        internalState.calcHarga();
        displayHarga();
    }//GEN-LAST:event_areaComboBoxActionPerformed

    private void namaPemesanTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaPemesanTextFieldKeyTyped
        // TODO add your handling code here:
        internalState.namaPemesan = namaPemesanTextField.getText()+ evt.getKeyChar();
    }//GEN-LAST:event_namaPemesanTextFieldKeyTyped

    private void luasTanahTersediaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_luasTanahTersediaTextFieldKeyTyped
        // TODO add your handling code here:
        try{
            String tanahTersedia = luasTanahTersediaTextField.getText();
            if ("1234567890".contains(String.valueOf(evt.getKeyChar())))
                tanahTersedia+=evt.getKeyChar();
            internalState.luasTanahTersedia = Integer.parseInt(tanahTersedia);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        internalState.calcHarga();
        displayHarga();
    }//GEN-LAST:event_luasTanahTersediaTextFieldKeyTyped

    private void dpTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dpTextFieldKeyTyped
        // TODO add your handling code here:
        try{
            String dp = dpTextField.getText();
            if ("1234567890".contains(String.valueOf(evt.getKeyChar())))
                dp+=evt.getKeyChar();
            internalState.dp = Integer.parseInt(dp);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        internalState.calcHarga();
        displayHarga();
    }//GEN-LAST:event_dpTextFieldKeyTyped

    private void lamaCicilanTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lamaCicilanTextFieldKeyTyped
        // TODO add your handling code here:
        try{
            String lamaCicilan = lamaCicilanTextField.getText();
            if ("1234567890".contains(String.valueOf(evt.getKeyChar())))
                lamaCicilan+=evt.getKeyChar();
            internalState.lamaCicilan = Integer.parseInt(lamaCicilan);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        internalState.calcHarga();
        displayHarga();
    }//GEN-LAST:event_lamaCicilanTextFieldKeyTyped

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection conn = DriverManager.getConnection(url, user, password)) {
                try (java.sql.Statement stmt = conn.createStatement()) {
                String query = "INSERT INTO penjualan "
                        + "(nama_pemesan, area, tipe_rumah, "
                        + "luas_tanah, harga, lama_cicilan, cicilan) "
                        + "VALUES "
                        + "('" + internalState.namaPemesan + "', '"
                        + internalState.area + "', '"
                        + internalState.tipeRumah + "', "
                        + internalState.luasTanahTersedia + ", "
                        + internalState.harga + ", "
                        + internalState.lamaCicilan + ", "
                        + internalState.cicilanBln + ");";
                    stmt.execute(query);
                    JOptionPane.showMessageDialog(
                            this,
                            "Sukses menyimpan data",
                            "Sukses",
                            JOptionPane.PLAIN_MESSAGE
                    );
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Gagal menyimpan data", 
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE
            );
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        if (internalState.setuju) setujuCheckBox.doClick();
        internalState = new FormState();
        namaPemesanTextField.setText("");
        tipeRumahGroup.clearSelection();
        luasTanahAsliTextField.setText("");
        luasTanahTersediaTextField.setText("");
        dpTextField.setText("");
        lamaCicilanTextField.setText("");
        displayHarga();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fetchDataPencarian();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        PenjualanRumahPanel.setVisible(false);
        tampilDataPanel.setVisible(false);
        cariDataPanel.setVisible(true);
        fetchDataPencarian();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection conn = DriverManager.getConnection(url, user, password)) {
                try (java.sql.Statement stmt = conn.createStatement()) {
                    String query = "SELECT * FROM penjualan ORDER BY id ASC";
                    File rootDir = new File(".");
                    var reportDirPath = rootDir.getCanonicalPath()+"\\src\\report\\";
                    var design = JRXmlLoader.load(reportDirPath+"HomelyReport.jrxml");
                    var report = JasperCompileManager.compileReport(design);
                    var res = stmt.executeQuery(query);
                    var resultSetDataSource = new JRResultSetDataSource(res);
                    var printed = JasperFillManager.fillReport(report, new HashMap<String, Object>(), resultSetDataSource);
                    JasperViewer.viewReport(printed);
                }
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Gagal mencetak report", 
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE
            );
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void displayHarga(){
        hargaTextField.setText(nf.format(internalState.harga));
        ppnTextField.setText(nf.format(internalState.ppn));
        cicilanTextField.setText(nf.format(internalState.getCicilanBln()));
    }
    
    private void fetchDataPenjualan(){
        var tabelModel = (javax.swing.table.DefaultTableModel) daftarPenjualanTable.getModel();
        tabelModel.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection conn = DriverManager.getConnection(url, user, password)) {
                try (java.sql.Statement stmt = conn.createStatement()) {
                    String query = "SELECT * FROM penjualan ORDER BY id ASC";
                    var res = stmt.executeQuery(query);
                    dataTabel.clear();
                    int jumlahPenjualan = 0;
                    long totalPenjualan = 0;
                    while (res.next()){
                        var data = new DataPenjualan(
                                res.getInt("id"),
                                res.getString("nama_pemesan"),
                                res.getString("area"),
                                res.getString("tipe_rumah"),
                                res.getInt("luas_tanah"),
                                res.getInt("harga"),
                                res.getInt("lama_cicilan"),
                                res.getInt("cicilan")
                        );
                        dataTabel.add(data);
                        tabelModel.addRow(data.toRowData());
                        jumlahPenjualan++;
                        totalPenjualan += data.harga;
                    }
                    jumlahRumahTerjualTextField.setText(""+jumlahPenjualan);
                    totalPenjualanRumahTextField.setText(nf.format(totalPenjualan));
                }
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Gagal mengambil data", 
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE
            );
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void fetchDataPencarian(){
        var tabelModel = (javax.swing.table.DefaultTableModel) daftarPenjualanTable1.getModel();
        tabelModel.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection conn = DriverManager.getConnection(url, user, password)) {
                try (java.sql.Statement stmt = conn.createStatement()) {
                    String query = "SELECT * FROM penjualan WHERE TRUE ";
                    var pemesanKey = cariPemesanTextField.getText();
                    var areaKey = cariAreaTextField.getText();
                    if (!pemesanKey.isEmpty())
                        query += "AND nama_pemesan LIKE '%"+pemesanKey+"%' ";
                    if (!areaKey.isEmpty())
                        query +=  "AND area LIKE '%"+areaKey+"%' ";
                    query += " ORDER BY id ASC";
                    var res = stmt.executeQuery(query);
                    dataTabelPencarian.clear();
                    int jumlahPenjualan = 0;
                    long totalPenjualan = 0;
                    while (res.next()){
                        var data = new DataPenjualan(
                                res.getInt("id"),
                                res.getString("nama_pemesan"),
                                res.getString("area"),
                                res.getString("tipe_rumah"),
                                res.getInt("luas_tanah"),
                                res.getInt("harga"),
                                res.getInt("lama_cicilan"),
                                res.getInt("cicilan")
                        );
                        dataTabelPencarian.add(data);
                        tabelModel.addRow(data.toRowData());
                        jumlahPenjualan++;
                        totalPenjualan += data.harga;
                    }
                    jumlahRumahTerjualTextField1.setText(""+jumlahPenjualan);
                    totalPenjualanRumahTextField1.setText(nf.format(totalPenjualan));
                }
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Gagal mengambil data", 
                    "Gagal",
                    JOptionPane.ERROR_MESSAGE
            );
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PenjualanRumahMenuItem;
    private javax.swing.JPanel PenjualanRumahPanel;
    private javax.swing.JComboBox<String> areaComboBox;
    private javax.swing.JTextField cariAreaTextField;
    private javax.swing.JPanel cariDataPanel;
    private javax.swing.JPanel cariDataSubpanel;
    private javax.swing.JTextField cariPemesanTextField;
    private javax.swing.JTextField cicilanTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTable daftarPenjualanTable;
    private javax.swing.JTable daftarPenjualanTable1;
    private javax.swing.JTextField dpTextField;
    private javax.swing.JTextField hargaBangunanTextField;
    private javax.swing.JTextField hargaTanahTextField;
    private javax.swing.JTextField hargaTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jumlahRumahTerjualTextField;
    private javax.swing.JTextField jumlahRumahTerjualTextField1;
    private javax.swing.JTextField lamaCicilanTextField;
    private javax.swing.JTextField luasTanahAsliTextField;
    private javax.swing.JTextField luasTanahTersediaTextField;
    private javax.swing.JTextField namaPemesanTextField;
    private javax.swing.JTextField ppnTextField;
    private javax.swing.JButton prosesButton;
    private javax.swing.JCheckBox setujuCheckBox;
    private javax.swing.JButton simpanButton;
    private javax.swing.JMenuItem tampilDataMenuItem;
    private javax.swing.JPanel tampilDataPanel;
    private javax.swing.ButtonGroup tipeRumahGroup;
    private javax.swing.JTextField totalPenjualanRumahTextField;
    private javax.swing.JTextField totalPenjualanRumahTextField1;
    // End of variables declaration//GEN-END:variables
}
